name: l3build
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  l3build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12]
    steps:
      - uses: actions/checkout@v3
      - uses: teatimeguest/setup-texlive-action@v2.5.1
        with:
          update-all-packages: true
          package-file: DEPENDS.txt
          packages: scheme-basic xetex libertine l3build microtype href-ul docshots pgfopts environ hypdoc etoolbox
      - run: l3build ctan --show-log-on-error --halt-on-error || echo fail
      - run: cat build/doc/fail-fast.log
      - uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: build/distrib/tds/tex/latex
          clean: true
        if: github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-20.04'
